### ISSUE TITLE
Deploy to Netlify 

### ISSUE THREAD

**Issue by sdmccloskey** [danielmahon/gatsby-starter-procyon#4]
Any idea on what I'm doing wrong here?

Netlify Deployment details:

5:00:03 PM:   TypeError: Only absolute URLs are supported
5:00:03 PM:   
5:00:03 PM:   - index.js:1268 getNodeRequestOptions
5:00:03 PM:     [repo]/[node-fetch]/lib/index.js:1268:9
5:00:03 PM:   
5:00:03 PM:   - index.js:1352 
5:00:03 PM:     [repo]/[node-fetch]/lib/index.js:1352:19
5:00:03 PM:   
5:00:03 PM:   - debuggability.js:303 Promise._execute
5:00:03 PM:     [repo]/[bluebird]/js/release/debuggability.js:303:9
5:00:03 PM:   
5:00:03 PM:   - promise.js:483 Promise._resolveFromExecutor
5:00:03 PM:     [repo]/[bluebird]/js/release/promise.js:483:18
5:00:03 PM:   
5:00:03 PM:   - promise.js:79 new Promise
5:00:03 PM:     [repo]/[bluebird]/js/release/promise.js:79:10
5:00:03 PM:   
5:00:03 PM:   - index.js:1349 Object.fetch
5:00:03 PM:     [repo]/[node-fetch]/lib/index.js:1349:9
5:00:03 PM:   
5:00:03 PM:   - node-ponyfill.js:9 Object.fetch
5:00:03 PM:     [repo]/[cross-fetch]/dist/node-ponyfill.js:9:20
5:00:03 PM:   
5:00:03 PM:   - index.js:104 GraphQLClient.<anonymous>
5:00:03 PM:     [repo]/[graphql-request]/dist/src/index.js:104:46
5:00:03 PM:   
5:00:03 PM:   - index.js:40 step
5:00:03 PM:     [repo]/[graphql-request]/dist/src/index.js:40:23
5:00:03 PM:   
5:00:03 PM:   - index.js:21 Object.next
5:00:03 PM:     [repo]/[graphql-request]/dist/src/index.js:21:53
5:00:04 PM:   
5:00:04 PM:   - index.js:15 
5:00:04 PM:     [repo]/[graphql-request]/dist/src/index.js:15:71
5:00:04 PM:   
5:00:04 PM:   - es6-promise.js:458 initializePromise
5:00:04 PM:     [repo]/[es6-promise]/dist/es6-promise.js:458:5
5:00:04 PM:   
5:00:04 PM:   - es6-promise.js:874 new Promise
5:00:04 PM:     [repo]/[es6-promise]/dist/es6-promise.js:874:33
5:00:04 PM:   
5:00:04 PM:   - index.js:11 __awaiter
5:00:04 PM:     [repo]/[graphql-request]/dist/src/index.js:11:12
5:00:04 PM:   
5:00:04 PM:   - index.js:94 GraphQLClient.request
5:00:04 PM:     [repo]/[graphql-request]/dist/src/index.js:94:16
5:00:04 PM:   
5:00:04 PM:   - gatsby-node.js:37 Object.<anonymous>
5:00:04 PM:     [repo]/[gatsby-source-graphcms]/gatsby-node.js:37:44
5:00:04 PM:   
5:00:04 PM: 
5:00:04 PM: Caching artifacts
5:00:04 PM: Started saving node modules
5:00:04 PM: Finished saving node modules
5:00:04 PM: Started saving yarn cache
5:00:04 PM: Finished saving yarn cache
5:00:04 PM: Started saving pip cache
5:00:04 PM: Finished saving pip cache
5:00:04 PM: Started saving emacs cask dependencies
5:00:04 PM: Finished saving emacs cask dependencies
5:00:04 PM: Started saving maven dependencies
5:00:04 PM: Finished saving maven dependencies
5:00:04 PM: Started saving boot dependencies
5:00:04 PM: Finished saving boot dependencies
5:00:04 PM: Started saving go dependencies
5:00:04 PM: Finished saving go dependencies
5:00:04 PM: Cached node version v8.11.1
5:00:04 PM: Error running command: Build script returned non-zero exit code: 1
5:00:04 PM: Failing build: Failed to build site
5:00:04 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
5:00:04 PM: Finished processing build request in 49.745890283s

**Comment by danielmahon** [comment]
@sdmccloskey Looks like its being called from line 37 `component: slash(postTemplate),`.  Check that line 12 `const postTemplate = path.resolve(`src/templates/post.js`);` is returning an absolute path. That is, if your `gatsby-node.js` is still the same as the template. Can you do a local build and serve? `gatsby build` and `gatsby serve`. Make sure that works before you try to push to netlify.

**Comment by sdmccloskey** [comment]
Build and Serve works great. Only issues is when deploying. @danielmahon

**Comment by danielmahon** [comment]
@sdmccloskey Did you add your ENV variables to Netlify? https://www.netlify.com/docs/continuous-deployment/#build-environment-variables. The `.env.production` file is just for `gatsby serve` and probably shouldnt be checked into your source. Usually no `.env` files should be checked in.

**Comment by sdmccloskey** [comment]
@danielmahon I do not. How do they look in key value pairs when adding to netlify?

![screenshot 2018-04-25 15 59 44](https://user-images.githubusercontent.com/12145022/39269757-b976c50e-48a1-11e8-8341-8e2007e28671.png)

**Comment by danielmahon** [comment]
Key = `GATSBY_GRAPHQLCMS_ENDPOINT`
Value = `https://api.graphcms.com/simple/v1/your-project`

**Comment by sdmccloskey** [comment]
Worked and added the token. Thank you. You can close this issue. @danielmahon
