### ISSUE TITLE
Error: Cannot query field "allPosts" or "allAuthors" on type "Query"

### ISSUE THREAD

**Issue by bensonnalle** [danielmahon/gatsby-starter-procyon#9]
When I run npm start for the first time after setting up the .env.development and .env.production files I get the following error: 
<img width="556" alt="screen shot 2018-07-20 at 4 10 58 pm" src="https://user-images.githubusercontent.com/19784422/43023064-84a19690-8c37-11e8-9698-400b1f709eda.png">

Any idea of what the problem could be? I haven't messed around with the GraphQL query.

**Comment by bensonnalle** [comment]
This error was a result of how I set up my Schema for GraphCMS. I didn't use the blog template (couldn't find it) so the query didn't match up with the structure of my CMS.

**Comment by cassiewallace** [comment]
Hey @bensonnalle -- I can't find the blog template either, looks like the features have changed on GraphCMS and their documentation is out of date as well. Were you able to create the schema correctly from scratch?

**Comment by bensonnalle** [comment]
Since the blog template is no longer available I customized the query to include the names of the fields for the schema I created. I found that easier than creating the schema to fit the original query.

My query in the gatsbyconfig now looks like this (and the other queries had to be adjusted too):
<img width="206" alt="screen shot 2018-09-26 at 3 49 54 pm" src="https://user-images.githubusercontent.com/19784422/46105395-db6d3f00-c1a3-11e8-857a-ecb194704c7e.png">

**Comment by cassiewallace** [comment]
Thank you!
